name: 'Deploy modal & update commands'

on:
  push:
    branches:
      - main
    # paths:
    #   - 'src/**'
    #   - '.github/workflows/deploy-discord-bot.yml'
    #   - 'app.py'
    #   - 'package-lock.json'

jobs:
  modal:
    name: 'Deploy to Modal'
    runs-on: ubuntu-latest
    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET  }}
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Modal 
        run: pip install modal
      
      - name: Deploy to Modal
        run: modal deploy app.py

  commands:
    name: 'Update Discord commands'
    runs-on: ubuntu-latest
    needs: modal
    env:
      DISCORD_APP_ID: ${{ secrets.DISCORD_APP_ID  }}
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN  }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
      
      - name: Register Discord Commands
        run: npm run discord:register-commands
