name: 'Build & Deploy Lambda'

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: 'Build Zip file'
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Create zip file
        run: zip -r elzip ./index.mjs ./node_modules/ ./src/ package.json package-lock.json

      - name: 'Upload Zip file for next job'
        uses: actions/upload-artifact@v4
        with:
          name: elzip
          path: ./elzip.zip
          if-no-files-found: error
          retention-days: 1

  deploy:
    name: 'Update Lambda from Zip file'
    runs-on: ubuntu-latest
    needs: build
    env:
      DISCORD_APP_ID: ${{ secrets.DISCORD_APP_ID  }}
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN  }}

    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: elzip
      
      - name: Display folder to check artifact
        run: ls -ll


      - name: Configure AWS Credentials for China region audience
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::058264239687:role/lasActionsDeNTNai

      - name: Deploy to lambda
        run: aws lambda update-function-code --function-name ntnBot --zip-file fileb://elzip.zip
