name: 'Build & Deploy Lambda'

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: 'Build Zip file'
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Create zip file
        run: zip -r elzip ./index.mjs ./node_modules/ ./src/ package.json package-lock.json

      - name: 'Upload Zip file for next job'
        uses: actions/upload-artifact@v4
        with:
          name: elzip
          path: ./elzip.zip
          if-no-files-found: error
          retention-days: 1

  deploy:
    name: 'Update Lambda from Zip file'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download the Zip artifact
        uses: actions/download-artifact@v4
        with:
          name: elzip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME  }}

      - name: Deploy to lambda via Zip file
        run: aws lambda update-function-code --function-name ntnBot --zip-file fileb://elzip.zip
